BCC 4 - Architecture initial and updates. Deploys automagically on AWS
trader-g/trader-g pull request #3
Opened 2024-03-11 13:06 UTC by KeeganOReilly

Commits show history.

2024-03-11 16:37 UTC, GerniVisser-bbd submitted a review, later dismissed

2024-03-12 06:19 UTC, Thato-Tladi approved these changes, later dismissed

2024-03-12 09:05 UTC, GerniVisser-bbd approved these changes

2024-03-12 09:29 UTC, GerniVisser-bbd requested changes

2024-03-12 09:29 UTC, GerniVisser-bbd commented on trader-g-api/target/classes/com/traderg/tradergapi/TraderGApiApplication.class
Remove these please

2024-03-12 09:29 UTC, GerniVisser-bbd commented on trader-g-api/target/test-classes/com/traderg/tradergapi/TraderGApiApplicationTests.class
Aswell as this

2024-03-12 09:29 UTC, GerniVisser-bbd commented on pom.xml
pom has to be in beancards. not sure what impact this would have on your other stuff

2024-03-12 09:29 UTC, GerniVisser-bbd commented on cli/pom.xml
> +    <maven.compiler.source>17</maven.compiler.source>
We should stick to one version of java and I believe Rudolf said to use Java 21

2024-03-12 11:50 UTC, GerniVisser-bbd approved these changes

2024-03-12 14:22 UTC, Thato-Tladi approved these changes

2024-03-12 14:23 UTC, merged